repository_type: pipeline

nf_core_version: 3.3.2

lint: {}

template:
  org: nf-core
  name: genomeannotation
  description: Simple functional annotation of genomes
  author: "@timrozday-mgnify"
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
